# Generated by Django 4.2.2 on 2023-07-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_product_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
